### ISSUE TITLE
nwjs Publish: filter is not a function

### ISSUE THREAD

**Issue by bejonwe** [karikera/vscode-nwjs-debug#11]
I just installed the new update (1.0.10) and when I try to publish I get the following error: 

```
TypeError: filter is not a function
    at ver (C:\Users\Jonathan\.vscode\extensions\ruakr.vsc-nwjs-1.0.10\out\src\nwjs\nwjs.js:314:45)
    at Array.filter (native)
    at C:\Users\Jonathan\.vscode\extensions\ruakr.vsc-nwjs-1.0.10\out\src\nwjs\nwjs.js:352:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Jonathan\.vscode\extensions\ruakr.vsc-nwjs-1.0.10\out\src\nwjs\nwjs.js:4:58)
```

I tried it with a simple project with just one html file and one JavaScript file and the nwjs version v0.24.3.

**Comment by karikera** [comment]
Oh, Sorry about late confirmation,
i will merge it, thanks!!
