### ISSUE TITLE
[debugger-for-chrome] Error processing "launch": TypeError: Cannot read property 'Windows' of undefined

### ISSUE THREAD

**Issue by Spown** [karikera/vscode-nwjs-debug#18]
After last update launch fails with an error
```
Error processing "launch": TypeError: Cannot read property 'Windows' of undefined
    at ChromeDebugAdapter.spawnChrome (C:\Users\____\.vscode\extensions\ruakr.vsc-nwjs-1.0.14\out\src\chromeDebugAdapter.js:217:105)
    at launch.then (C:\Users\____\.vscode\extensions\ruakr.vsc-nwjs-1.0.14\out\src\chromeDebugAdapter.js:106:37)
    at <anonymous>
```

**Comment by karikera** [comment]
Oh, Thanks for bug report.
I fixed it in 1.0.15 update!
